# Generated by Django 5.2 on 2025-05-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_created_at_category_updated_at'),
        ('subcategory', '0002_alter_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category'),
        ),
    ]
