# Generated by Django 5.2 on 2025-05-10 15:01

import django.db.models.deletion
import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'db_table': 'attribute',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('contact_details', models.TextField()),
                ('logo', models.ImageField(upload_to=settings.models.store_path)),
                ('banner_1', models.ImageField(upload_to=settings.models.store_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StoreInfo',
                'verbose_name_plural': 'StoreInfo',
                'db_table': 'store_info',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UnitType',
                'verbose_name_plural': 'UnitTypes',
                'db_table': 'unit_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_items', to='settings.attribute')),
            ],
            options={
                'verbose_name': ('AttributeItem',),
                'verbose_name_plural': 'AttributeItems',
                'db_table': 'attribute_item',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_galleries', to='settings.storeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to=settings.models.store_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='settings.storeinfo')),
            ],
            options={
                'verbose_name': 'SocialMedia',
                'verbose_name_plural': 'SocialMedia',
                'db_table': 'social_media',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=settings.models.store_path)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_gallery_uploads', to='settings.storegallery')),
            ],
        ),
    ]
