# Generated by Django 5.2 on 2025-05-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storegallery',
            options={'ordering': ['-id'], 'verbose_name': 'StoreGallery', 'verbose_name_plural': 'StoreGalleries'},
        ),
        migrations.AlterModelOptions(
            name='storeupload',
            options={'ordering': ['-id'], 'verbose_name': 'StoreUpload', 'verbose_name_plural': 'StoreUploads'},
        ),
        migrations.AlterModelTable(
            name='storegallery',
            table='store_gallery',
        ),
        migrations.AlterModelTable(
            name='storeupload',
            table='store_upload',
        ),
        migrations.CreateModel(
            name='ExtraPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('page_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pages', to='settings.storeinfo')),
            ],
            options={
                'verbose_name': 'ExtraPage',
                'verbose_name_plural': 'ExtraPages',
                'db_table': 'extra_page',
                'ordering': ['-id'],
            },
        ),
    ]
